### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by BusinessUsername420666** [RegressiveIsProgressive/BTC-BSC-RegressiveWalletCrackers#2]
hello, would like to test. can run 24/7 .. how do we get in touch?

**Comment by parlamenter** [comment]
I want test too

**Comment by RegressiveIsProgressive** [comment]
> hello, would like to test. can run 24/7 .. how do we get in touch? 

Potentially reinitiating testing under new parameters. Reach out if interest exist in participation.

**Comment by RegressiveIsProgressive** [comment]
> I want test too

Reach out if interest existing in testing.
